### ISSUE TITLE
App stuck because Computer is not turned on

### ISSUE THREAD

**Issue by ikbendewilliam** [91team/computer#14]
We've integrated computer in our app and on iOS the app is stuck on the splash screen. After some looking the issue seems to be that the computer hasn't started yet.
```dart
  Future<Map<String, dynamic>> decode(String encoded) async {
    if (!computer.isRunning) {
      print('computer isn\'t turned on yet'); // <-- This is printed
    }
    return computer.compute<String, Map<String, dynamic>>(parseAndDecode, param: encoded);
  }
```
I would expect the package to either wait in the compute function until the computer is available or, if that's to hard, throw an exception so that we know why the app stopped functioning. Now it just waits forever.

**Comment by TheVinhLuong** [comment]
Hi @ikbendewilliam, is this still an issue for you?

**Comment by ikbendewilliam** [comment]
@TheVinhLuong in the end we went native for the project I used this for. I do know my colleague ended up using compute and I don't think they encountered this issue. So for me it's fine to close for now :-)
