### ISSUE TITLE
compute() without an argument passes null to a called method

### ISSUE THREAD

**Issue by Shakle** [91team/computer#7]
Hi, listened to your flutter podcast on google podcasts. Very interesting, great work and easy to use.

for example:

```
int countNumbers() {
    return 1 + 2; 
}
int number = await Computer().compute(countNumbers);
```
It ill try to call countNumbers(null) and it will give an error **NoSuchMethodFound**;

As a workAround I currently use 

int countNumbers(null) {
    return 1 + 2; 
}

Please try something not to require that argument if I have no arguments in the method.
Did not find any info in the description that a method must be a top level function.

**Comment by Stalder** [comment]
@Shakle Hi, thanks! Sounds like a silly mistake, i will fix it tomorrow. The only trouble about that is there are already other changes in repo, which are not published. So, looks like tomorrow with this fix some breaking changes will be landed

**Comment by dmitriismitnov** [comment]
Is this issue relevant now? I see a test with a similar case and it is succeeded

https://github.com/91team/computer/blob/master/test/computer_test.dart#L71
