### ISSUE TITLE
Unique exception for cancelled tasks

### ISSUE THREAD

**Issue by JetA2** [91team/computer#9]
Hi, thanks for the great package! Simple and very easy to use.

It would be nice to have a different exception thrown when tasks are cancelled when turnOff is called so a cancellation can be separated from exceptions thrown in the compute function.

**Comment by dmitriismitnov** [comment]
@JetA2 Hi. Is this issue relevant for you now?

**Comment by JetA2** [comment]
Hi, yes I'm still using your package so it would be a nice addition.

**Comment by dmitriismitnov** [comment]
@JetA2  Sorry for the long wait https://github.com/91team/computer/pull/16.

`3.2.0 in the pub`

**Comment by JetA2** [comment]
Nice, many thanks!

**Comment by JetA2** [comment]
The exception works great but it's not exported, therefore the import 'package:computer/src/errors.dart' is needed.
This works fine but produces a linter recommendation (https://dart-lang.github.io/linter/lints/implementation_imports.html).

While everything still works it would be nice to have the exceptions exported to silence this recommendation.
